// <auto-generated />
namespace Cradle.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class NewFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201603271347389_New Fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
